---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    #network_mode: host
    ports:
       - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    #network_mode: host
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${DOCKER_MACHINE_IP}:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_MACHINE_IP}:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

  kclient:
    image: oldenbur/kclient
    #network_mode: host
    depends_on:
      - kafka
    environment:
      KCLIENT_BROKER: ${DOCKER_MACHINE_IP}:29092
      KCLIENT_TOPIC: foo
      KCLIENT_GROUP: group1
    extra_hosts:
      - "moby:127.0.0.1"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
